### ISSUE TITLE
Not showing Background tab

### ISSUE THREAD

**Issue by juanpasolano** [NewSpring/react-storybook-addon-backgrounds#18]
Hi,
I just install the addon following the instructions on readme but nothing is happening, not even an error.

```
    "react": "15.0.1",
    "@kadira/storybook": "^2.21.0"
    "react-storybook-addon-backgrounds": "0.0.4",
```

**Comment by jbaxleyiii** [comment]
@juanpasolano did you create an `addons.js` file and import the `react-storybook-addon-backgrounds/register` file?

**Comment by juanpasolano** [comment]
I was adding the addons to the wrong folder.
Thank you.
