### ISSUE TITLE
Would love to see some getting started docs

### ISSUE THREAD

**Issue by arunoda** [NewSpring/react-storybook-addon-backgrounds#8]
And send a PR to here once you've a good version of this addon: https://github.com/kadirahq/getstorybook.io/blob/master/src/docs/addons/addon-gallery.js

**Comment by jbaxleyiii** [comment]
@arunoda you bet 👍

**Comment by jbaxleyiii** [comment]
@arunoda added! We are going to finish some tests and write an article about it tomorrow! I'll send a PR then
