### ISSUE TITLE
Add the current color to the query string.

### ISSUE THREAD

**Issue by arunoda** [NewSpring/react-storybook-addon-backgrounds#9]
You can add the current selected color to the queryString.
See: https://getstorybook.io/docs/addons/api#storybookapi-setqueryparams-

Additionally you can save it to browser as well.

**Comment by jbaxleyiii** [comment]
> Additionally you can save it to browser as well.

How would we go about doing this?

**Comment by arunoda** [comment]
For the browser stuff, you need to use the localstorage or cookies manually. We don't have a API for that.
